"""add workflow_versions table and capture workflow tags

Revision ID: 450ba5f04530
Revises: f94ac13cc6b5
Create Date: 2026-04-28 20:07:18.982396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "450ba5f04530"
down_revision: Union[str, Sequence[str], None] = "f94ac13cc6b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("yaml_content", sa.Text(), nullable=False),
        sa.Column(
            "definition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "registered_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("registered_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_name", "version", name="uq_workflow_versions_name_version"
        ),
    )
    op.create_index(
        op.f("ix_workflow_versions_workflow_name"),
        "workflow_versions",
        ["workflow_name"],
        unique=False,
    )
    op.add_column("captures", sa.Column("workflow_name", sa.String(), nullable=True))
    op.add_column(
        "captures", sa.Column("workflow_version", sa.Integer(), nullable=True)
    )
    op.add_column(
        "captures", sa.Column("sample_qa_flagged", sa.Boolean(), nullable=True)
    )
    op.create_index(
        op.f("ix_captures_workflow_name"), "captures", ["workflow_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_captures_workflow_name"), table_name="captures")
    op.drop_column("captures", "sample_qa_flagged")
    op.drop_column("captures", "workflow_version")
    op.drop_column("captures", "workflow_name")
    op.drop_index(
        op.f("ix_workflow_versions_workflow_name"), table_name="workflow_versions"
    )
    op.drop_table("workflow_versions")
    # ### end Alembic commands ###
