"""initial captures and corrections schema

Revision ID: f94ac13cc6b5
Revises:
Create Date: 2026-04-27 22:53:03.318519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f94ac13cc6b5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "captures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column(
            "input_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "output_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("agent_version", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_captures_started_at",
        "captures",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_captures_status"), "captures", ["status"], unique=False)
    op.create_index(
        op.f("ix_captures_task_name"), "captures", ["task_name"], unique=False
    )
    op.create_table(
        "corrections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("capture_id", sa.UUID(), nullable=False),
        sa.Column(
            "original_output_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "edited_output_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("edit_severity", sa.Float(), nullable=False),
        sa.Column("reviewer_id", sa.String(), nullable=False),
        sa.Column("edit_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("submitted_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corrections_capture_id"), "corrections", ["capture_id"], unique=False
    )
    op.create_index(
        op.f("ix_corrections_reviewer_id"), "corrections", ["reviewer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_corrections_reviewer_id"), table_name="corrections")
    op.drop_index(op.f("ix_corrections_capture_id"), table_name="corrections")
    op.drop_table("corrections")
    op.drop_index(op.f("ix_captures_task_name"), table_name="captures")
    op.drop_index(op.f("ix_captures_status"), table_name="captures")
    op.drop_index("ix_captures_started_at", table_name="captures")
    op.drop_table("captures")
    # ### end Alembic commands ###
